09_ROK, reference, 01_production, x, 06_crude_oil_and_ngl: ''
09_ROK, reference, 02_imports, x, 06_crude_oil_and_ngl: ''
09_ROK, reference, 02_imports, x, 08_gas: ''
09_ROK, reference, 02_imports, x, 16_others: ''
09_ROK, reference, 02_imports, x, 19_total: ''
09_ROK, reference, 04_international_marine_bunkers, x, 08_gas: ''
09_ROK, reference, 05_international_aviation_bunkers, x, 07_petroleum_products: ''
09_ROK, reference, 05_international_aviation_bunkers, x, 19_total: ''
09_ROK, reference, 07_total_primary_energy_supply, x, 01_coal: ''
09_ROK, reference, 07_total_primary_energy_supply, x, 06_crude_oil_and_ngl: ''
09_ROK, reference, 07_total_primary_energy_supply, x, 07_petroleum_products: ''
09_ROK, reference, 07_total_primary_energy_supply, x, 19_total: ''
09_ROK, reference, 09_total_transformation_sector_negative, 09_02_chp_plants, 19_total: ''
09_ROK, reference, 09_total_transformation_sector_negative, x, 19_total: ''
09_ROK, reference, 09_total_transformation_sector_positive, 09_02_chp_plants, 17_electricity: ''
09_ROK, reference, 09_total_transformation_sector_positive, 09_02_chp_plants, 18_heat: ''
09_ROK, reference, 09_total_transformation_sector_positive, 09_02_chp_plants, 21_modern_renewables: ''
09_ROK, reference, 10_losses_and_own_use, 10_01_own_use, 07_petroleum_products: ''
09_ROK, reference, 10_losses_and_own_use, 10_02_transmission_and_distribution_losses, 18_heat: ''
09_ROK, reference, 15_transport_sector, 15_01_domestic_air_transport, 17_electricity: ''
09_ROK, reference, 15_transport_sector, 15_01_domestic_air_transport, 19_total: ''
09_ROK, reference, 15_transport_sector, 15_01_domestic_air_transport, 21_modern_renewables: ''
09_ROK, reference, 15_transport_sector, 15_02_road, 19_total: ''
09_ROK, reference, 15_transport_sector, 15_02_road, 20_total_renewables: ''
09_ROK, reference, 15_transport_sector, 15_02_road, 21_modern_renewables: ''
09_ROK, reference, 15_transport_sector, 15_03_rail, 16_others: ''
09_ROK, reference, 15_transport_sector, 15_03_rail, 17_electricity: ''
09_ROK, reference, 15_transport_sector, 15_03_rail, 19_total: ''
09_ROK, reference, 15_transport_sector, 15_03_rail, 20_total_renewables: ''
09_ROK, reference, 15_transport_sector, 15_03_rail, 21_modern_renewables: ''
09_ROK, reference, 15_transport_sector, 15_04_domestic_navigation, 16_others: ''
09_ROK, reference, 15_transport_sector, 15_04_domestic_navigation, 17_electricity: ''
09_ROK, reference, 15_transport_sector, 15_04_domestic_navigation, 19_total: ''
09_ROK, reference, 15_transport_sector, 15_04_domestic_navigation, 20_total_renewables: ''
09_ROK, reference, 15_transport_sector, 15_04_domestic_navigation, 21_modern_renewables: ''
09_ROK, reference, 16_other_sector, 16_02_agriculture_and_fishing, 08_gas: ''
09_ROK, reference, 16_other_sector, 16_02_agriculture_and_fishing, 15_solid_biomass: ''
09_ROK, reference, 18_electricity_output_in_gwh, 18_01_electricity_plants, 01_coal: ''
09_ROK, reference, 18_electricity_output_in_gwh, 18_01_electricity_plants, 19_total: ''
09_ROK, reference, 18_electricity_output_in_gwh, 18_01_electricity_plants, 20_total_renewables: ''
09_ROK, reference, 18_electricity_output_in_gwh, 18_01_electricity_plants, 21_modern_renewables: ''
09_ROK, reference, 18_electricity_output_in_gwh, 18_02_chp_plants, 08_gas: ''
09_ROK, reference, 18_electricity_output_in_gwh, 18_02_chp_plants, 19_total: ''
09_ROK, reference, 19_heat_output_in_pj, 19_01_chp_plants, 06_crude_oil_and_ngl: ''
09_ROK, reference, 19_heat_output_in_pj, 19_01_chp_plants, 08_gas: ''
09_ROK, reference, 19_heat_output_in_pj, 19_01_chp_plants, 19_total: ''
09_ROK, reference, 19_heat_output_in_pj, 19_01_chp_plants, 20_total_renewables: ''
09_ROK, reference, 19_heat_output_in_pj, 19_01_chp_plants, 21_modern_renewables: ''
09_ROK, reference, 19_heat_output_in_pj, x, 20_total_renewables: ''
09_ROK, reference, 19_heat_output_in_pj, x, 21_modern_renewables: ''
09_ROK, target, 01_production, x, 06_crude_oil_and_ngl: ''
09_ROK, target, 02_imports, x, 01_coal: ''
09_ROK, target, 02_imports, x, 06_crude_oil_and_ngl: ''
09_ROK, target, 02_imports, x, 08_gas: ''
09_ROK, target, 02_imports, x, 16_others: ''
09_ROK, target, 02_imports, x, 19_total: ''
09_ROK, target, 04_international_marine_bunkers, x, 08_gas: ''
09_ROK, target, 05_international_aviation_bunkers, x, 07_petroleum_products: ''
09_ROK, target, 05_international_aviation_bunkers, x, 19_total: ''
09_ROK, target, 07_total_primary_energy_supply, x, 01_coal: ''
09_ROK, target, 07_total_primary_energy_supply, x, 02_coal_products: ''
09_ROK, target, 07_total_primary_energy_supply, x, 06_crude_oil_and_ngl: ''
09_ROK, target, 07_total_primary_energy_supply, x, 07_petroleum_products: ''
09_ROK, target, 07_total_primary_energy_supply, x, 19_total: ''
09_ROK, target, 09_total_transformation_sector_negative, 09_02_chp_plants, 19_total: ''
09_ROK, target, 09_total_transformation_sector_negative, x, 19_total: ''
09_ROK, target, 09_total_transformation_sector_positive, 09_02_chp_plants, 17_electricity: ''
09_ROK, target, 09_total_transformation_sector_positive, 09_02_chp_plants, 18_heat: ''
09_ROK, target, 09_total_transformation_sector_positive, 09_02_chp_plants, 21_modern_renewables: ''
09_ROK, target, 09_total_transformation_sector_positive, 09_13_hydrogen_transformation, 08_gas: ''
09_ROK, target, 09_total_transformation_sector_positive, 09_13_hydrogen_transformation, 16_others: ''
09_ROK, target, 09_total_transformation_sector_positive, 09_13_hydrogen_transformation, 19_total: ''
09_ROK, target, 10_losses_and_own_use, 10_01_own_use, 07_petroleum_products: ''
09_ROK, target, 10_losses_and_own_use, 10_02_transmission_and_distribution_losses, 18_heat: ''
09_ROK, target, 14_industry_sector, 14_03_manufacturing, 19_total: ''
09_ROK, target, 15_transport_sector, 15_01_domestic_air_transport, 16_others: ''
09_ROK, target, 15_transport_sector, 15_01_domestic_air_transport, 17_electricity: ''
09_ROK, target, 15_transport_sector, 15_01_domestic_air_transport, 19_total: ''
09_ROK, target, 15_transport_sector, 15_01_domestic_air_transport, 21_modern_renewables: ''
09_ROK, target, 15_transport_sector, 15_02_road, 16_others: ''
09_ROK, target, 15_transport_sector, 15_02_road, 19_total: ''
09_ROK, target, 15_transport_sector, 15_02_road, 20_total_renewables: ''
09_ROK, target, 15_transport_sector, 15_02_road, 21_modern_renewables: ''
09_ROK, target, 15_transport_sector, 15_03_rail, 16_others: ''
09_ROK, target, 15_transport_sector, 15_03_rail, 17_electricity: ''
09_ROK, target, 15_transport_sector, 15_03_rail, 19_total: ''
09_ROK, target, 15_transport_sector, 15_03_rail, 20_total_renewables: ''
09_ROK, target, 15_transport_sector, 15_03_rail, 21_modern_renewables: ''
09_ROK, target, 15_transport_sector, 15_04_domestic_navigation, 16_others: ''
09_ROK, target, 15_transport_sector, 15_04_domestic_navigation, 17_electricity: ''
09_ROK, target, 15_transport_sector, 15_04_domestic_navigation, 19_total: ''
09_ROK, target, 15_transport_sector, 15_04_domestic_navigation, 20_total_renewables: ''
09_ROK, target, 15_transport_sector, 15_04_domestic_navigation, 21_modern_renewables: ''
09_ROK, target, 15_transport_sector, x, 20_total_renewables: ''
09_ROK, target, 15_transport_sector, x, 21_modern_renewables: ''
09_ROK, target, 16_other_sector, 16_02_agriculture_and_fishing, 08_gas: ''
09_ROK, target, 16_other_sector, 16_02_agriculture_and_fishing, 15_solid_biomass: ''
09_ROK, target, 18_electricity_output_in_gwh, 18_01_electricity_plants, 01_coal: ''
09_ROK, target, 18_electricity_output_in_gwh, 18_01_electricity_plants, 19_total: ''
09_ROK, target, 18_electricity_output_in_gwh, 18_01_electricity_plants, 20_total_renewables: ''
09_ROK, target, 18_electricity_output_in_gwh, 18_01_electricity_plants, 21_modern_renewables: ''
09_ROK, target, 18_electricity_output_in_gwh, 18_02_chp_plants, 08_gas: ''
09_ROK, target, 18_electricity_output_in_gwh, 18_02_chp_plants, 19_total: ''
09_ROK, target, 19_heat_output_in_pj, 19_01_chp_plants, 06_crude_oil_and_ngl: ''
09_ROK, target, 19_heat_output_in_pj, 19_01_chp_plants, 08_gas: ''
09_ROK, target, 19_heat_output_in_pj, 19_01_chp_plants, 19_total: ''
09_ROK, target, 19_heat_output_in_pj, 19_01_chp_plants, 20_total_renewables: ''
09_ROK, target, 19_heat_output_in_pj, 19_01_chp_plants, 21_modern_renewables: ''
09_ROK, target, 19_heat_output_in_pj, x, 20_total_renewables: ''
09_ROK, target, 19_heat_output_in_pj, x, 21_modern_renewables: ''
09_ROK, reference, 09_total_transformation_sector_negative, 09_12_nonspecified_transformation, 01_coal: ''
09_ROK, reference, 09_total_transformation_sector_negative, 09_12_nonspecified_transformation, 08_gas: ''
09_ROK, reference, 09_total_transformation_sector_positive, 09_01_electricity_plants, 21_modern_renewables: ''
09_ROK, reference, 11_statistical_discrepancy, x, 17_electricity: ''
09_ROK, target, 09_total_transformation_sector_negative, 09_12_nonspecified_transformation, 01_coal: ''
09_ROK, target, 09_total_transformation_sector_negative, 09_12_nonspecified_transformation, 08_gas: ''
09_ROK, target, 09_total_transformation_sector_positive, 09_01_electricity_plants, 21_modern_renewables: ''
09_ROK, target, 11_statistical_discrepancy, x, 17_electricity: ''

#########################

21_VN, reference, 01_production, x, 14_wind, x: ''
21_VN, reference, 01_production, x, 15_solid_biomass, 15_solid_biomass_unallocated: ''
21_VN, reference, 01_production, x, 16_others, 16_05_biogasoline: ''
21_VN, reference, 01_production, x, 16_others, 16_06_biodiesel: ''
21_VN, reference, 01_production, x, 16_others, 16_07_bio_jet_kerosene: ''
21_VN, reference, 01_production, x, 17_x_green_electricity, x: ''
21_VN, reference, 02_imports, x, 01_coal, 01_x_thermal_coal: ''
21_VN, reference, 02_imports, x, 06_crude_oil_and_ngl, 06_01_crude_oil: ''
21_VN, reference, 02_imports, x, 07_petroleum_products, 07_x_other_petroleum_products: ''
21_VN, reference, 02_imports, x, 15_solid_biomass, 15_03_charcoal: ''
21_VN, reference, 03_exports, x, 01_coal, 01_x_thermal_coal: ''
21_VN, reference, 03_exports, x, 06_crude_oil_and_ngl, 06_01_crude_oil: ''
21_VN, reference, 09_total_transformation_sector_negative, 09_07_oil_refineries, 06_crude_oil_and_ngl, 06_01_crude_oil: ''
? 21_VN, reference, 09_total_transformation_sector_positive, 09_07_oil_refineries,
  07_petroleum_products, 07_01_motor_gasoline
: ''
21_VN, reference, 09_total_transformation_sector_positive, 09_07_oil_refineries, 07_petroleum_products, 07_09_lpg: ''
21_VN, reference, 09_total_transformation_sector_positive, 09_07_oil_refineries, 07_petroleum_products, 07_x_jet_fuel: ''
21_VN, reference, 09_total_transformation_sector_positive, 09_13_hydrogen_transformation, 16_others, 16_x_hydrogen: ''
21_VN, reference, 10_losses_and_own_use, 10_01_own_use, 17_electricity, x: ''
21_VN, reference, 14_industry_sector, 14_03_manufacturing, 07_petroleum_products, 07_07_gas_diesel_oil: ''
21_VN, reference, 15_transport_sector, 15_01_domestic_air_transport, 16_others, 16_07_bio_jet_kerosene: ''
21_VN, reference, 15_transport_sector, 15_02_road, 16_others, 16_05_biogasoline: ''
21_VN, reference, 15_transport_sector, 15_02_road, 16_others, 16_06_biodiesel: ''
21_VN, reference, 15_transport_sector, 15_02_road, 16_others, 16_x_hydrogen: ''
21_VN, reference, 15_transport_sector, 15_02_road, 17_electricity, x: ''
21_VN, reference, 15_transport_sector, 15_03_rail, 07_petroleum_products, 07_07_gas_diesel_oil: ''
21_VN, reference, 15_transport_sector, 15_03_rail, 16_others, 16_06_biodiesel: ''
21_VN, reference, 15_transport_sector, 15_03_rail, 17_electricity, x: ''
21_VN, reference, 15_transport_sector, 15_04_domestic_navigation, 07_petroleum_products, 07_07_gas_diesel_oil: ''
21_VN, reference, 15_transport_sector, 15_04_domestic_navigation, 07_petroleum_products, 07_08_fuel_oil: ''
21_VN, reference, 15_transport_sector, 15_04_domestic_navigation, 16_others, 16_06_biodiesel: ''
21_VN, reference, 18_electricity_output_in_gwh, 18_01_electricity_plants, 01_coal, 01_coal_unallocated: ''
21_VN, reference, 18_electricity_output_in_gwh, 18_01_electricity_plants, 08_gas, 08_gas_unallocated: ''
21_VN, reference, 18_electricity_output_in_gwh, 18_01_electricity_plants, 14_wind, x: ''
21_VN, reference, 18_electricity_output_in_gwh, 18_01_electricity_plants, 15_solid_biomass, 15_solid_biomass_unallocated: ''
21_VN, target, 01_production, x, 14_wind, x: ''
21_VN, target, 01_production, x, 15_solid_biomass, 15_solid_biomass_unallocated: ''
21_VN, target, 01_production, x, 16_others, 16_05_biogasoline: ''
21_VN, target, 01_production, x, 16_others, 16_06_biodiesel: ''
21_VN, target, 01_production, x, 16_others, 16_07_bio_jet_kerosene: ''
21_VN, target, 01_production, x, 17_x_green_electricity, x: ''
21_VN, target, 02_imports, x, 01_coal, 01_x_thermal_coal: ''
21_VN, target, 02_imports, x, 07_petroleum_products, 07_x_other_petroleum_products: ''
21_VN, target, 02_imports, x, 08_gas, 08_02_lng: ''
21_VN, target, 02_imports, x, 15_solid_biomass, 15_03_charcoal: ''
21_VN, target, 03_exports, x, 01_coal, 01_x_thermal_coal: ''
21_VN, target, 09_total_transformation_sector_negative, 09_07_oil_refineries, 06_crude_oil_and_ngl, 06_01_crude_oil: ''
21_VN, target, 09_total_transformation_sector_positive, 09_06_gas_processing_plants, 08_gas, 08_01_natural_gas: ''
21_VN, target, 09_total_transformation_sector_positive, 09_07_oil_refineries, 07_petroleum_products, 07_01_motor_gasoline: ''
21_VN, target, 09_total_transformation_sector_positive, 09_07_oil_refineries, 07_petroleum_products, 07_07_gas_diesel_oil: ''
21_VN, target, 09_total_transformation_sector_positive, 09_07_oil_refineries, 07_petroleum_products, 07_09_lpg: ''
21_VN, target, 09_total_transformation_sector_positive, 09_07_oil_refineries, 07_petroleum_products, 07_x_jet_fuel: ''
21_VN, target, 09_total_transformation_sector_positive, 09_13_hydrogen_transformation, 16_others, 16_x_hydrogen: ''
21_VN, target, 10_losses_and_own_use, 10_01_own_use, 17_electricity, x: ''
21_VN, target, 14_industry_sector, 14_03_manufacturing, 07_petroleum_products, 07_07_gas_diesel_oil: ''
21_VN, target, 15_transport_sector, 15_01_domestic_air_transport, 16_others, 16_07_bio_jet_kerosene: ''
21_VN, target, 15_transport_sector, 15_01_domestic_air_transport, 17_electricity, x: ''
21_VN, target, 15_transport_sector, 15_02_road, 16_others, 16_05_biogasoline: ''
21_VN, target, 15_transport_sector, 15_02_road, 16_others, 16_06_biodiesel: ''
21_VN, target, 15_transport_sector, 15_02_road, 16_others, 16_x_hydrogen: ''
21_VN, target, 15_transport_sector, 15_02_road, 17_electricity, x: ''
21_VN, target, 15_transport_sector, 15_03_rail, 07_petroleum_products, 07_07_gas_diesel_oil: ''
21_VN, target, 15_transport_sector, 15_03_rail, 16_others, 16_06_biodiesel: ''
21_VN, target, 15_transport_sector, 15_03_rail, 17_electricity, x: ''
21_VN, target, 15_transport_sector, 15_04_domestic_navigation, 07_petroleum_products, 07_07_gas_diesel_oil: ''
21_VN, target, 15_transport_sector, 15_04_domestic_navigation, 07_petroleum_products, 07_08_fuel_oil: ''
21_VN, target, 15_transport_sector, 15_04_domestic_navigation, 16_others, 16_06_biodiesel: ''
21_VN, target, 15_transport_sector, 15_04_domestic_navigation, 17_electricity, x: ''
21_VN, target, 18_electricity_output_in_gwh, 18_01_electricity_plants, 01_coal, 01_coal_unallocated: ''
21_VN, target, 18_electricity_output_in_gwh, 18_01_electricity_plants, 08_gas, 08_gas_unallocated: ''
21_VN, target, 18_electricity_output_in_gwh, 18_01_electricity_plants, 14_wind, x: ''
21_VN, target, 18_electricity_output_in_gwh, 18_01_electricity_plants, 15_solid_biomass, 15_solid_biomass_unallocated: ''
