name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - python = 3.10
  - jupyterlab
  - matplotlib
  - pandas
  - openpyxl
  - xlsxwriter
  - seaborn
  - pandasdmx
  - requests
  - urllib3
  - wbgapi
  - sympy