name: Outlook9th_EBT
# conda env create --prefix ./env --file ./config/environment.yml
channels:
  - conda-forge
  - defaults

dependencies:
  - python = 3.10
  - jupyterlab
  - matplotlib
  - pandas
  - numpy
  - openpyxl
  - xlsxwriter
  - seaborn
  - pandasdmx
  - requests
  - urllib3
  - wbgapi
  - sympy